# Permalinks
permalink:           pretty

# Setup
title:               e0015274
tagline:             A Moderately Okay Data Science Blog
url:                 http://e0015274.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              e0015274
  url:               https://twitter.com/e0015274
  email:             e0015274@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/e0015274

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
